params ["_this"];

[ _this,
	[
		"RB205_DC15A","RB205_DC15A_GL","RB205_DC15C","RB205_DC15C_GL","RB205_DC15L","RB205_DC15S","RB205_DC15X","RB205_DC17M","RB205_DP23","RB205_Valken38X","RB205_WestarM5","RB205_Z6","RB205_BTX42","RB205_DC15S_JLTS","twc_2inch_bag","RB205_PLX1_F","RB205_RPS6","RB205_RPS6_disposable","RB205_DC17","RB205_DC17_alt","RB205_DC17_Dual","JLTS_DC17SA","UNSC_Knife","UNSC_Knife_reversed","ACE_Flashlight_Maglite_ML300L","hgun_esd_01_F","ACE_VMM3",
		"3AS_optic_holo_DC15S","3AS_Optic_Scope_WestarM5","SEA_Optic_Holo_Two_Red","SEA_Optic_Holo_Two_Blue","SEA_Optic_Holo_Two_Green","SEA_Optic_Holo_One_Green","JLTS_DC15X_scope","SEA_Optic_Holo_One_Red","3AS_optic_acog_DC15C","3AS_optic_reflex_DC15C","RB205_Optic_DC15L","SEA_Optic_Holo_One_Blue","RB205_attachment_scope_DC17M_sniper","SEA_Optic_Holo_One_Yellow","RB205_Optic_VK38X","SEA_Optic_Holo_Two_Yellow","OPTRE_M7_Laser","acc_pointer_IR","OPTRE_BMR_Laser","JLTS_DC17SA_flashlight","acc_flashlight","ACE_DBAL_A3_Green","acc_flashlight_pistol","OPTRE_M45_Flashlight","OPTRE_M7_Flashlight","OPTRE_M6C_Laser","OPTRE_M6G_Flashlight","OPTRE_M12_Laser","ACE_DBAL_A3_Red","ACE_SPIR","ACE_acc_pointer_green","RB205_DC15X_Suppressor","RB205_attachment_DC17M_blaster","RB205_attachment_DC17M_at","RB205_attachment_DC17M_sniper","3AS_Bipod_VK38X_f","3AS_Bipod_DC15L_f","muzzle_antenna_03_f","muzzle_antenna_01_f","muzzle_antenna_02_f",
		"RB205_Scatter_Energy_Pack","3Rnd_SmokeBlue_Grenade_shell","3Rnd_SmokeGreen_Grenade_shell","RB205_Overcharged_Energy_Pack","JLTS_stun_mag_short","RB205_Standard_Energy_Pack","3Rnd_SmokeRed_Grenade_shell","ACE_40mm_Flare_red","RB205_RapidFire_Energy_Pack","ACE_40mm_Flare_white","RB205_DC17M_AT_Mag","RB205_BTX42_mag","3AS_6Rnd_HE_Grenade_shell","twc_2inch_he_1rnd","3Rnd_HE_Grenade_shell","RB205_Compact_Energy_Pack","3Rnd_SmokePurple_Grenade_shell","RB205_Heavy_Energy_Pack","RB205_Experimental_Energy_Pack","JLTS_stun_mag_long","RB205_DC17M_Sniper_Mag","3Rnd_SmokeYellow_Grenade_shell","RB205_MK39_AA","ACE_40mm_Flare_green","RB205_MAG_RPS6","3Rnd_Smoke_Grenade_shell","ACE_HuntIR_M203","3Rnd_SmokeOrange_Grenade_shell","RB205_DC17M_Blaster_Mag","WBK_Cybercrystal",

		"RB205_thermalDet","RB205_impactGren","RB205_sonicDet","RB205_droidPopper","RB205_smokeWhite","RB205_smokeBlue","RB205_smokeGreen","RB205_smokeRed","RB205_smokeYellow","RB205_smokePurple","RB205_smokeOrange",
		"ACE_Chemlight_White","Chemlight_blue","Chemlight_green","Chemlight_red","ACE_Chemlight_Orange","Chemlight_yellow","ACE_Chemlight_HiWhite","ACE_Chemlight_HiBlue","ACE_Chemlight_HiGreen","ACE_Chemlight_HiRed","ACE_Chemlight_HiYellow","ACE_Chemlight_UltraHiOrange","ACE_Chemlight_IR",
		"ShieldGrenade_Mag","ShieldGrenadePersonal_Mag","SquadShieldMagazine",
		"APERSMine_Range_Mag","ACE_FlareTripMine_Mag","TrainingMine_Mag","IEDUrbanSmall_Remote_Mag","IEDLandSmall_Remote_Mag","APERSTripMine_Wire_Mag","SLAMDirectionalMine_Wire_Mag","M41_IED_B_Remote_Mag","M41_IED_Remote_Mag","M41_IED_C_Remote_Mag","ClaymoreDirectionalMine_Remote_Mag","APERSBoundingMine_Range_Mag","SatchelCharge_Remote_Mag","M168_Remote_Mag","UNSCMine_Range_Mag","ATMine_Range_Mag","DemoCharge_Remote_Mag","IEDUrbanBig_Remote_Mag","IEDLandBig_Remote_Mag","JLTS_explosive_emp_50_mag","JLTS_explosive_emp_20_mag","JLTS_explosive_emp_10_mag","ls_mag_demo_remoteCharge","JMSLLTE_Detonitecharge_imp_Mag","ls_mag_detPack_remoteCharge","SWLW_DetPack_remote_mag","SWLW_clones_spec_demo_mag","LFP_mine_ap_Mag","LFP_mine_at_Mag","ls_mag_caltrops_dispenser","ls_mag_caltrops_mine","C12_Remote_Mag","C7_Remote_Mag","SWLW_clones_spec_breach_mag","ls_mag_breach_remoteCharge","APERSMineDispenser_Mag","RTX_RemoteMagazine","HX_AT_Mine_Mag","EC01_RemoteMagazine","3AS_DetPack","Aux212_X3_Thermal_Disruptor","Aux212_X10_Thermal_Disruptor","Aux212_7PrG_Proton_Charge","knd_ATMine_Mag","knd_ClassC_Plant_Mag","knd_ClassB_Plant_Mag","knd_ClassA_Plant_Mag","knd_BoundingMines_Mag","knd_Daisy_Mag","knd_Claymore_Mag","knd_Breacher_Mag","LFP_type_A_Remote_Mag","LFP_type_B_Remote_Mag","LFP_type_C_Remote_Mag","212th_MPC_MK1_F"
	]
] call ace_arsenal_fnc_initBox;